on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x' 
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/app-arm64-v8a-debug.apk"
        tag: v1.04
        token: ${{ secrets.TOKEN }}
    - name: Upload Artifact To Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
          appId: ${{ secrets.FIREBASE_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: "Debug"
          releaseNotesFile: README.md
          file: build/app/outputs/apk/debug/app-arm64-v8a-debug.apk
          debug: true
